/*
 * SistemaLiquidaciondeHaberesView.java
 */

package sistemaliquidaciondehaberes;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class SistemaLiquidaciondeHaberesView extends FrameView {

    public SistemaLiquidaciondeHaberesView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = SistemaLiquidaciondeHaberesApp.getApplication().getMainFrame();
            aboutBox = new SistemaLiquidaciondeHaberesAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        SistemaLiquidaciondeHaberesApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        mainPanel.setName("mainPanel"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        menuBar.setName("menuBar"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sistemaliquidaciondehaberes.SistemaLiquidaciondeHaberesApp.class).getContext().getResourceMap(SistemaLiquidaciondeHaberesView.class);
        fileMenu.setText(resourceMap.getString("MenuInicio.text")); // NOI18N
        fileMenu.setName("MenuInicio"); // NOI18N

        jMenuItem1.setText(resourceMap.getString("jm_Inicio.text")); // NOI18N
        jMenuItem1.setName("jm_Inicio"); // NOI18N
        fileMenu.add(jMenuItem1);

        jMenuItem2.setText(resourceMap.getString("text")); // NOI18N
        jMenuItem2.setName(""); // NOI18N
        fileMenu.add(jMenuItem2);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(sistemaliquidaciondehaberes.SistemaLiquidaciondeHaberesApp.class).getContext().getActionMap(SistemaLiquidaciondeHaberesView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setText(resourceMap.getString("exitMenuItem.text")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        jMenu1.setText(resourceMap.getString("Menu_Empleados.text")); // NOI18N
        jMenu1.setName("Menu_Empleados"); // NOI18N

        jMenuItem3.setText(resourceMap.getString("M_it_Empl_Alta.text")); // NOI18N
        jMenuItem3.setName("M_it_Empl_Alta"); // NOI18N
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText(resourceMap.getString("M_it_Empl_Baja.text")); // NOI18N
        jMenuItem4.setName("M_it_Empl_Baja"); // NOI18N
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText(resourceMap.getString("M_it_Empl_Modif.text")); // NOI18N
        jMenuItem5.setName("M_it_Empl_Modif"); // NOI18N
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText(resourceMap.getString("M_it_Empl_Buscar.text")); // NOI18N
        jMenuItem6.setName("M_it_Empl_Buscar"); // NOI18N
        jMenu1.add(jMenuItem6);

        menuBar.add(jMenu1);

        jMenu2.setText(resourceMap.getString("M_it_Leg_Alta.text")); // NOI18N
        jMenu2.setName("M_it_Leg_Alta"); // NOI18N

        jMenuItem7.setText(resourceMap.getString("jMenuItem7.text")); // NOI18N
        jMenuItem7.setName("jMenuItem7"); // NOI18N
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText(resourceMap.getString("M_it_Leg_CambEstado.text")); // NOI18N
        jMenuItem8.setName("M_it_Leg_CambEstado"); // NOI18N
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText(resourceMap.getString("M_it_Leg_AgreNovedades.text")); // NOI18N
        jMenuItem9.setName("M_it_Leg_AgreNovedades"); // NOI18N
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText(resourceMap.getString("M_it_Leg_ModifNovedades.text")); // NOI18N
        jMenuItem10.setName("M_it_Leg_ModifNovedades"); // NOI18N
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText(resourceMap.getString("M_it_Leg_Detalle.text")); // NOI18N
        jMenuItem11.setName("M_it_Leg_Detalle"); // NOI18N
        jMenu2.add(jMenuItem11);

        menuBar.add(jMenu2);

        jMenu3.setText(resourceMap.getString("M_it_Liquidacion_Total.text")); // NOI18N
        jMenu3.setName("M_it_Liquidacion_Total"); // NOI18N

        jMenuItem12.setText(resourceMap.getString("jMenuItem12.text")); // NOI18N
        jMenuItem12.setName("jMenuItem12"); // NOI18N
        jMenu3.add(jMenuItem12);

        jMenuItem13.setText(resourceMap.getString("M_it_Liquidacion_Parcial.text")); // NOI18N
        jMenuItem13.setName("M_it_Liquidacion_Parcial"); // NOI18N
        jMenu3.add(jMenuItem13);

        jMenu4.setText(resourceMap.getString("M_it_Liquidacion_ItemMenu.text")); // NOI18N
        jMenu4.setName("M_it_Liquidacion_ItemMenu"); // NOI18N

        jMenuItem14.setText(resourceMap.getString("ItemMenu_Alta.text")); // NOI18N
        jMenuItem14.setName("ItemMenu_Alta"); // NOI18N
        jMenu4.add(jMenuItem14);

        jMenuItem15.setText(resourceMap.getString("ItemMenu_Baja.text")); // NOI18N
        jMenuItem15.setName("ItemMenu_Baja"); // NOI18N
        jMenu4.add(jMenuItem15);

        jMenuItem16.setText(resourceMap.getString("ItemMenu_Modificaciones.text")); // NOI18N
        jMenuItem16.setName("ItemMenu_Modificaciones"); // NOI18N
        jMenu4.add(jMenuItem16);

        jMenuItem17.setText(resourceMap.getString("ItemMenu_Lista.text")); // NOI18N
        jMenuItem17.setName("ItemMenu_Lista"); // NOI18N
        jMenu4.add(jMenuItem17);

        jMenu3.add(jMenu4);

        menuBar.add(jMenu3);

        jMenu5.setText(resourceMap.getString("Menu_CargasSociales.text")); // NOI18N
        jMenu5.setName("Menu_CargasSociales"); // NOI18N

        jMenu6.setText(resourceMap.getString("It_ObraSocial.text")); // NOI18N
        jMenu6.setName("It_ObraSocial"); // NOI18N

        jMenuItem18.setText(resourceMap.getString("It_ObraSocial_Alta.text")); // NOI18N
        jMenuItem18.setName("It_ObraSocial_Alta"); // NOI18N
        jMenu6.add(jMenuItem18);

        jMenuItem19.setText(resourceMap.getString("It_ObraSocial_Baja.text")); // NOI18N
        jMenuItem19.setName("It_ObraSocial_Baja"); // NOI18N
        jMenu6.add(jMenuItem19);

        jMenuItem20.setText(resourceMap.getString("It_ObraSocial_Modificaciones.text")); // NOI18N
        jMenuItem20.setName("It_ObraSocial_Modificaciones"); // NOI18N
        jMenu6.add(jMenuItem20);

        jMenuItem21.setText(resourceMap.getString("It_ObraSocial_Lista.text")); // NOI18N
        jMenuItem21.setName("It_ObraSocial_Lista"); // NOI18N
        jMenu6.add(jMenuItem21);

        jMenu5.add(jMenu6);

        jMenu7.setText(resourceMap.getString("It_Sindicatos.text")); // NOI18N
        jMenu7.setName("It_Sindicatos"); // NOI18N

        jMenuItem22.setText(resourceMap.getString("It_Sindicatos_Alta.text")); // NOI18N
        jMenuItem22.setName("It_Sindicatos_Alta"); // NOI18N
        jMenu7.add(jMenuItem22);

        jMenuItem23.setText(resourceMap.getString("It_Sindicatos_Baja.text")); // NOI18N
        jMenuItem23.setName("It_Sindicatos_Baja"); // NOI18N
        jMenu7.add(jMenuItem23);

        jMenuItem24.setText(resourceMap.getString("It_Sindicatos_Modificaciones.text")); // NOI18N
        jMenuItem24.setName("It_Sindicatos_Modificaciones"); // NOI18N
        jMenu7.add(jMenuItem24);

        jMenuItem25.setText(resourceMap.getString("It_Sindicatos_Lista.text")); // NOI18N
        jMenuItem25.setName("It_Sindicatos_Lista"); // NOI18N
        jMenu7.add(jMenuItem25);

        jMenu5.add(jMenu7);

        jMenu8.setText(resourceMap.getString("It_Jubilacion.text")); // NOI18N
        jMenu8.setName("It_Jubilacion"); // NOI18N

        jMenuItem26.setText(resourceMap.getString("It_Jubilacion_Alta.text")); // NOI18N
        jMenuItem26.setName("It_Jubilacion_Alta"); // NOI18N
        jMenu8.add(jMenuItem26);

        jMenuItem27.setText(resourceMap.getString("It_Jubilacion_Baja.text")); // NOI18N
        jMenuItem27.setName("It_Jubilacion_Baja"); // NOI18N
        jMenu8.add(jMenuItem27);

        jMenuItem28.setText(resourceMap.getString("It_Jubilacion_Modificaciones.text")); // NOI18N
        jMenuItem28.setName("It_Jubilacion_Modificaciones"); // NOI18N
        jMenu8.add(jMenuItem28);

        jMenuItem29.setText(resourceMap.getString("It_Jubilacion_Lista.text")); // NOI18N
        jMenuItem29.setName("It_Jubilacion_Lista"); // NOI18N
        jMenu8.add(jMenuItem29);

        jMenu5.add(jMenu8);

        jMenu9.setText(resourceMap.getString("It_OtrasCargas.text")); // NOI18N
        jMenu9.setName("It_OtrasCargas"); // NOI18N

        jMenuItem30.setText(resourceMap.getString("It_OtrasCargas_Alta.text")); // NOI18N
        jMenuItem30.setName("It_OtrasCargas_Alta"); // NOI18N
        jMenu9.add(jMenuItem30);

        jMenuItem31.setText(resourceMap.getString("It_OtrasCargas_Baja.text")); // NOI18N
        jMenuItem31.setName("It_OtrasCargas_Baja"); // NOI18N
        jMenu9.add(jMenuItem31);

        jMenuItem32.setText(resourceMap.getString("It_OtrasCargas_Modificaciones.text")); // NOI18N
        jMenuItem32.setName("It_OtrasCargas_Modificaciones"); // NOI18N
        jMenu9.add(jMenuItem32);

        jMenuItem33.setText(resourceMap.getString("It_OtrasCargas_Lista.text")); // NOI18N
        jMenuItem33.setName("It_OtrasCargas_Lista"); // NOI18N
        jMenu9.add(jMenuItem33);

        jMenu5.add(jMenu9);

        menuBar.add(jMenu5);

        jMenu10.setText(resourceMap.getString("Menu_Cargos.text")); // NOI18N
        jMenu10.setName("Menu_Cargos"); // NOI18N

        jMenuItem35.setText(resourceMap.getString("It_Cargos_Alta.text")); // NOI18N
        jMenuItem35.setName("It_Cargos_Alta"); // NOI18N
        jMenu10.add(jMenuItem35);

        jMenuItem36.setText(resourceMap.getString("It_Cargos_Baja.text")); // NOI18N
        jMenuItem36.setName("It_Cargos_Baja"); // NOI18N
        jMenu10.add(jMenuItem36);

        jMenuItem37.setText(resourceMap.getString("It_Cargos_Modificaciones.text")); // NOI18N
        jMenuItem37.setName("It_Cargos_Modificaciones"); // NOI18N
        jMenu10.add(jMenuItem37);

        jMenuItem38.setText(resourceMap.getString("It_Cargos_Lista.text")); // NOI18N
        jMenuItem38.setName("It_Cargos_Lista"); // NOI18N
        jMenu10.add(jMenuItem38);

        menuBar.add(jMenu10);

        helpMenu.setText(resourceMap.getString("Menu_Ayuda.text")); // NOI18N
        helpMenu.setName("Menu_Ayuda"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setText(resourceMap.getString("It_Ayuda_SobreNosotros.text")); // NOI18N
        aboutMenuItem.setName("It_Ayuda_SobreNosotros"); // NOI18N
        helpMenu.add(aboutMenuItem);

        jMenuItem34.setText(resourceMap.getString("It_Ayuda_Manual.text")); // NOI18N
        jMenuItem34.setName("It_Ayuda_Manual"); // NOI18N
        helpMenu.add(jMenuItem34);

        jMenuItem39.setText(resourceMap.getString("It_Ayuda_SitioWeb.text")); // NOI18N
        jMenuItem39.setName("It_Ayuda_SitioWeb"); // NOI18N
        helpMenu.add(jMenuItem39);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
